version: '3'
services:
  apache:
    build: ./apache
    container_name: apache_server
    ports:
      - "8080:80"

  nginx:
    build: ./nginx
    container_name: nginx_server
    ports:
      - "80:80"
    depends_on:
      - apache
