version: '3'
services:
  apache:
    build: ./apache
    container_name: apache_server
    ports:
      - "8080:80"

  nginx:
    build: ./nginx
    container_name: nginx_server
    ports:
      - "80:80"
    depends_on:
      - apache

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./apache/site/init.sql:/docker-entrypoint-initdb.d/init.sql

  
